### ISSUE TITLE
Customization of configurtations

### ISSUE THREAD

**Issue by zenny** [jthlim/javelin-steno-rp2040#1]
Hi @jthlim 

What a nifty admirable work! Thanks! New to steno, so bear with me.

Recently, I came across two posts where some of the nice customization on the Uni v4, mentioned by Mirabai Knight (http://plover.stenoknight.com/2023/01/embedded-steno-on-my-uni.html) and dictionary modifications by Aerick (https://aerick.ca/steno/dictionary-building/). Aerick's multipurpose multisteno was on display in https://www.youtube.com/watch?v=fUFjBVekmj8 

It would be nice if somebody could point the necessary config changes from plover to your embedded steno setup?! Cheers, /z

**Comment by jthlim** [comment]
For configuring a firmware, it's recommended that you use https://lim.au/#/software/javelin-steno

You can add any dictionaries you want to your own build using that tool.

Embedded steno doesn't support modal dictionaries, but I think you're better off using a separate tool layer for navigation/selection: (See examples here: https://github.com/jthlim/javelin_steno_script/tree/main/scripts/uni_v4 -- they can be configured on the website above if you enable "show all options")
