### ISSUE TITLE
QMK Compatibility?

### ISSUE THREAD

**Issue by GaryBoone** [jthlim/javelin-steno-rp2040#2]
I’m very excited to see this project and have steno directly embedded in my keyboard. Would you describe the relationship of this firmware to QMK? Is it possible to use both? In your Reddit post [1], I see the mode switching from QWERTY to steno, (and there’s a macOS menu bar indicator here [2]), but how do you change the QWERTY key mappings? I think that’s what QMK/VIA are for? And how do you adjust the steno dictionaries?

[1] https://www.reddit.com/r/crkbd/s/yUgddHm49Y
[2] https://github.com/jthlim/javelin-steno-menubar

**Comment by jthlim** [comment]
There is no relationship between QMK and Javelin. They are two completely separate code bases, and the license between Javelin and QMK is not compatible.

Key maps are defined by scripts such as [these](https://github.com/jthlim/javelin_steno_script/blob/main/scripts/crkbd/crkbd.javelin-script)

Dictionaries are configured and built at the [online firmware tool](https://lim.au/#/software/javelin-steno)
