### ISSUE TITLE
How to provide a dictionary?

### ISSUE THREAD

**Issue by kerinin** [jthlim/javelin-steno-rp2040#3]
I see that it's possible to compile the firmware with arbitrary JSON dictionaries on the web tool (https://lim.au/#/software/javelin-steno) but I don't see any way to do so from the source code. I'm attempting to create a new keyboard config, so I can't use the web-based builder, but I would like to be able to control the dictionary (AFAICT the compiled `uf2` only has a very minimal dictionary).

**Comment by jthlim** [comment]
There's a project https://github.com/jthlim/plover_json_convert that converts dictionaries, but It hasn't been maintained

The recommended way, that has worked for several others, is just to use the website to build your dataset, upload it to your keyboard, then overwrite the firmware + button script with your own customized build.

Recommend that you jump on plover discord, under firmware-dev to discuss/search for how other people have achieved this in the past.
