### ISSUE TITLE
support for YASK?

### ISSUE THREAD

**Issue by tocklime** [jthlim/javelin-steno-rp2040#4]
[YASK](https://github.com/ttempe/YASK) is a RP2040-based steno DIY steno keyboard, where every key is wired to a different IO (similar to the starboard, i guess from reading the Javelin source). The [pinout is available here](https://github.com/ttempe/YASK/blob/main/YASK.py). I've had a go at trying to get javelin working on this, but can't figure out how the starboard goes from the bitmap of which keys are pressed in row-major order (`BUTTON_PINS`) to the set of Steno keys that that means are pressed (where is it that maps the S1 key to the first (or possibly second?, I'm not sure what the extra keys on the left side of the starboard are for) entry in `BUTTON_PINS`?

The v1 and v2 YASK have different key-pin assignments. I have a v2. 

Anyway, I'm happy to keep hacking around with things, but was hoping for some pointers.

**Comment by jthlim** [comment]
First, does the rp2040 used have 128Mbit of flash? If so, then this is the process:

1. Use the online firmware builder for a starboard firmware, then upload that to the board. This is to put the dictionaries & configuration on the device.
2. Copy the starboard.h config file and create a yask.h config file. Update the pin -> button mapping there.
3. Build and upload it to the yask. This will over write just the portion of the firmware related to the specific device configuration
4. Use the web script tool to upload the script that maps buttons -> steno keys.

The script is the key bit that you're probably missing. The default starboard script can be found here: https://github.com/jthlim/javelin_steno_script/blob/main/scripts/starboard/starboard.javelin-script
It is recommended to use the visual editor to set this up nowadays more easily.

Finally, if you still can't get it working, jump onto plover discord, firmware discussion channel. Several people have successfully made Javelin work with their own boards
